[package]
name = "bip324"
version = "0.2.0"
edition = "2021"
license-file = "LICENSE"
description = "Encrypted messaging over the Bitcoin P2P Protocol as specified by BIP 324"
repository = "https://github.com/rustaceanrob/bip324"
readme = "README.md"
rust-version = "1.56.1"

[features]
default = ["std"]
std = ["alloc", "secp256k1/std", "rand/std", "rand/std_rng"]
alloc = []

[dependencies]
secp256k1 = { version="0.29.0", default-features = false}
rand = { version = "0.8.0", default-features = false }
bitcoin = { version = "0.31.2", default-features = false, features = ["no-std"] }
bitcoin_hashes = { version = "0.14.0", default-features = false }

[dev-dependencies]
hex = { package = "hex-conservative", version = "0.2.0" }

[lib]
name = "bip324"
path = "src/lib.rs"

