[package]
name = "bip324-proxy"
version = "0.2.0"
edition = "2021"
license-file = "LICENSE"
description = "BIP324 proxy enabling v1-only clients to use the v2 Bitcoin P2P Protocol"
repository = "https://github.com/rustaceanrob/bip324"
readme = "README.md"
rust-version = "1.56.1"

[dependencies]
bitcoin = "0.31.1"
tokio = { version = "1.36.0", features = ["full"] }
bytes = "1.6.0"
hex = { package = "hex-conservative", version = "0.2.0" }
bip324 = { path = "../protocol", version = "0.2.0" }
