name: Cargo Build & Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Rust - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - name: Update Toolchain
        run: rustup default ${{ matrix.toolchain }} && rustup component add --toolchain ${{ matrix.toolchain }} rustfmt && rustup component add --toolchain ${{ matrix.toolchain }} clippy && rustup update ${{ matrix.toolchain }} 
      - name: Build
        run: cargo build --verbose
      - name: Lint
        run: cargo clippy --all --all-targets
      - name: Format
        run: cargo fmt --all -- --check
      - name: Test
        run: cargo test --verbose

        
